#!/bin/bash
if [ -z "${1##*.ipk}"  ]; then
	for i in $1; do
		mkdir -p /tmp/file-roller/$1
		cp $1 /tmp/file-roller/$1
		cd /tmp/file-roller/$1
		perl -le '($e,$f)=@ARGV;map{$o=$_;s/$e$/$f/;rename$o,$_}<*.$e>' ipk ar
		var=$(ls)
		file-roller $var && rm -r /tmp/file-roller/$1
	done
else
	file-roller $1
fi
