#! /bin/sh
# We want only one instance of mpv running. There is a python script "umpv" that provides this feature. 
# But lets just keep it simple ;)

i3-msg [class=mpv] kill

if [ "$(pidof neutrino)" ] 
then
  rcsim KEY_MUTEON && mpv --profile=pseudo-gui "$1" && rcsim KEY_MUTEOFF 
else
  mpv --profile=pseudo-gui "$1" && i3-msg workspace back_and_forth
fi
