#!/bin/sh

if [ ! -d ~/yocto-downloads ];then
	mkdir ~/yocto-downloads
fi
if [ ! -d ~/yocto ];then
	mkdir ~/yocto
fi
cd ~/yocto
if [ ! -d poky ];then
	git clone -b morty git://git.yoctoproject.org/poky
fi
cd poky
git checkout morty
if [ ! -d meta-neutrino ];then
		git clone -b morty https://github.com/neutrino-hd/meta-neutrino.git
else
	cd meta-neutrino && git checkout morty && cd ..
fi
if [ ! -d meta-coolstream ];then
	git clone -b morty https://github.com/neutrino-hd/meta-coolstream.git
else
	cd meta-coolstream && git checkout morty
fi
export TEMPLATECONF=meta-coolstream/example
cd ~/yocto/poky
. ./oe-init-build-env build-hd2 
