#!/bin/sh
#
# User's .xinitrc file

# Merge custom X resources
[[ -f ~/.Xresources ]] && xrdb -merge ~/.Xresources


# Set screen resolution

DISPLAY_1="DP1"
DISPLAY_2="DP2"
# Position of Display2 compared to Display1
POSITION="below"
SCALE="1.0x1.0"

xrandr --output $DISPLAY_1 --auto --output $DISPLAY_2 --scale $SCALE --auto --$POSITION $DISPLAY_1

# Map mod4 to win key
xmodmap -e "keycode 115 = Super_L" -e "add mod4 = Super_L"

# Start the window manager
feh --randomize --bg-fill ~/.wallpaper/*
exec ck-launch-session dbus-launch --sh-syntax --exit-with-session i3
